name: JMeter Test Execution

on: [push]

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JMeter
        run: |
          # Ensure JMeter directory exists in the repo
          if [ ! -d "./apache-jmeter-5.6.3" ]; then
            echo "JMeter directory not found! Ensure it is included in the repository."
            exit 1
          fi
          export JMETER_HOME=$PWD/apache-jmeter-5.6.3
          export PATH=$JMETER_HOME/bin:$PATH

      - name: Verify JMeter Installation
        run: |
          jmeter --version

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run JMeter Tests
        run: |
          jmeter -n -t ./apache-jmeter-5.6.3\apache-jmeter-5.6.3\.github\workflows\main.yml -l result.jtl -e -o ./reports/html/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-reports
          path: reports
          if-no-files-found: error

