name: JMeter Test Execution

on: 
  push:

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir reports

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter Tests
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t ${{ github.workspace }}/bin/project/opencart.jmx -l result.csv -e -o ./reports/html/

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.csv
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: reports
          if-no-files-found: error

