name: JMeter Test Execution

on: [push]

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run JMeter Tests
      uses: ./local-action
      with:
        test-plan-path: ./apache-jmeter-5.6.3/bin/project/opencar.jmx
        args: "-e -o ./reports/html/"

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: reports
        if-no-files-found: error
